# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_01RGUreZy_2kZ3tU8hBGQu-Vg8cgINH
"""

score = input().split()
max = score[0]
min = score[0]

countF = 0
for s in score:
  if int(s) += 1
print(countF)

if score[i] > max:
  max = score[i]
elif score[i] < min:
  min = score[i]

print('max:{max}min:{min}')