# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cyqQaSPYBBio5hOzEnMmmAqdTQtp4YZ
"""

score = input().split()

countF = 0
total = 0
for i in score:
    num = int(i)
    total += num
    if num < 60:
        countF += 1


average = total / len(score)

print(countF)
print(average)